### ISSUE TITLE
[Question] Multi layout manager

### ISSUE THREAD

**Issue by royt93** [MindorksOpenSource/ConcatAdapter-Android-Example#1]
Dear Team MindOrks.

Thanks for your great example, Im using MergeAdapter in my project and I have a question.
How can I initialize multi layout manager?
Ex:
recyclerView.layoutManager = LinearLayoutManager(context)
recyclerView.adapter = MergeAdapter(listOf(adapterA , adapterB))

I want the adapterA is displayed as LinearLayoutManager and the adapterB is displayed as GridLayoutManager.

Thank you.

**Comment by hi-manshu** [comment]
Hey @tplloi,
currently is not supported by the library. Once it's there, we will update the repo
